name: ohmo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: 3.0.9
  intl: 0.18.1
  flutter_svg: ^2.0.17
  image_picker: 1.1.2
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: 2.4.6

flutter:
  assets:
    - android/assets/images/cal_month.svg
    - android/assets/images/cal_week.svg
    - android/assets/images/plus.svg
    - android/assets/images/plus2.svg
    - android/assets/images/routine_alarm.svg
    - android/assets/images/todo_alarm.svg
    - android/assets/images/calendar_unselected.svg
    - android/assets/images/calendar_selected.svg
    - android/assets/images/daylog_unselected.svg
    - android/assets/images/daylog_selected.svg
    - android/assets/images/my_unselected.svg
    - android/assets/images/my_selected.svg
    - android/assets/images/happy_unselected.svg
    - android/assets/images/soso_unselected.svg
    - android/assets/images/bad_unselected.svg
    - android/assets/images/mybackground.svg
    - android/assets/images/myprofile.svg
    - android/assets/images/notion.svg
    - android/assets/images/profile_photo.svg
    - android/assets/images/background_edit.svg
    - android/assets/images/login_google.svg
    - android/assets/images/login_naver.svg
    - android/assets/images/login_kakao.svg


  uses-material-design: true
  fonts:
    - family: RubikSprayPaint
      fonts:
        - asset: android/assets/fonts/RubikSprayPaint-Regular.ttf
    - family: PretendardBold
      fonts:
        - asset: android/assets/fonts/Pretendard-Bold.ttf
    - family: PretendardRegular
      fonts:
        - asset: android/assets/fonts/Pretendard-Regular.ttf
    - family: PretendardSemiBold
      fonts:
        - asset: android/assets/fonts/Pretendard-SemiBold.ttf